version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "8000:8000" # Expose port 8000 to the host
    env_file:
      - .env
    volumes:
      - .:/app      # Mount the local directory into the container's /app directory
    command: ["npm", "run", "dev"]  # Ensure you're using a dev script (nodemon)
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres-service
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
