-- Create a table 'metrics'
CREATE TYPE public."enum_Metric_type" AS ENUM ('distance','temperature');
CREATE TABLE IF NOT EXISTS "Metric" (
    "id" serial4 NOT NULL,
	"date" varchar(255) NULL,
	"value" float8 NULL,
	"unit" varchar(255) NULL,
	"type" public."enum_Metric_type" NULL,
	"userId" varchar(255) NULL,
	"createdAt" timestamptz NOT NULL,
	"updatedAt" timestamptz NOT NULL,
	CONSTRAINT "Metric_pkey" PRIMARY KEY (id)
);

-- Insert data for December 2024 without using loops
INSERT INTO "Metric"  ("date" , "value" , "unit", "type", "userId" , "createdAt" , "updatedAt") VALUES
('2024-12-01', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-02', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-03', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-04', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-05', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-06', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-07', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-08', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-09', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-10', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-11', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-12', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-13', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-14', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-15', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-16', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-17', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-18', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-19', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-20', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-21', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-22', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-23', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-24', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-25', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-26', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-27', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-28', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-29', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-30', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW()),
('2024-12-31', round(CAST(random() * 100 AS numeric), 2), (ARRAY['m', 'cm', 'in', 'ft', 'yd'])[(floor(random() * 5) + 1)], 'distance', 'everfit', NOW(), NOW());

INSERT INTO "Metric"  ("date" , "value" , "unit", "type", "userId" , "createdAt" , "updatedAt") VALUES
('2024-12-01', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-02', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-03', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-04', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-05', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-06', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-07', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-08', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-09', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-10', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-11', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-12', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-13', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-14', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-15', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-16', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-17', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-18', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-19', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-20', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-21', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-22', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-23', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-24', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-25', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-26', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-27', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-28', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-29', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-30', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW()),
('2024-12-31', round(CAST(random() * 100 AS numeric), 2), (ARRAY['K', 'C', 'F'])[(floor(random() * 3) + 1)], 'temperature', 'everfit', NOW(), NOW());